spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_service
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#user-service:
#  url: http://user-service:8082
#
#patient-service:
#  url: http://patient-service:8084
#
#clinic-service:
#  url: http://clinic-service:8083
